spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: ${DB_POOL_NAME:IdentityService-HikariPool}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:5s}
      timeout: ${REDIS_TIMEOUT:5s}

api:
  security:
    token:
      secret: ${JWT_SECRET}

app:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

monitoring:
  prometheus:
    username: ${PROMETHEUS_USERNAME}
    password: ${PROMETHEUS_PASSWORD}

